name:                perpetual
version:             0.1.0.0
github:              "githubuser/perpetual"
license:             BSD3
author:              "Francisco Chaves"
maintainer:          "pachopepe@gmail.com"
copyright:           "2019 Francisco Chaves"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/perpetual#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3 && < 4
- ghc-prim >= 0.5 && < 0.6
- containers >= 0.6 && < 0.7
- time
- text

library:
  source-dirs: src

executables:
  perpetual-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - perpetual

tests:
  perpetual-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - perpetual
